global HDL_FILE_NAMES
set HDL_FILE_NAMES [list \
    "${HDL_DIR}/utilities.vhd" \
    "${HDL_DIR}/gray.vhd" \
    "${HDL_DIR}/sync.vhd" \
    "${HDL_DIR}/fifos.vhd" \
    "${HDL_DIR}/acc.vhd" \
    "${HDL_DIR}/demux.vhd" \
    "${HDL_DIR}/mult.vhd" \
    "${HDL_DIR}/mac.vhd" \
    "${HDL_DIR}/mux.vhd" \
    "${HDL_DIR}/onehot_binary.vhd" \
    "${HDL_DIR}/ram_dp.vhd" \
    "${HDL_DIR}/rr_arbiter.vhd" \
    "${HDL_DIR}/line_buffer.vhd" \
    "${HDL_DIR}/pe.vhd" \
    "${HDL_DIR}/psum_bias.vhd" \
    "${HDL_DIR}/psum_activation.vhd" \
    "${HDL_DIR}/psum_requantize.vhd" \
    "${HDL_DIR}/postproc.vhd" \
    "${HDL_DIR}/pe_array.vhd" \
    "${HDL_DIR}/ram_dp_bwe.vhd" \
    "${HDL_DIR}/ram_mw.vhd" \
    "${HDL_DIR}/spad_reshape.vhd" \
    "${HDL_DIR}/scratchpad.vhd" \
    "${HDL_DIR}/reformatter.vhd" \
    "${HDL_DIR}/parallelizer.vhd" \
    "${HDL_DIR}/serializer.vhd" \
    "${HDL_DIR}/scratchpad_interface.vhd" \
    "${HDL_DIR}/address_generator.vhd" \
    "${HDL_DIR}/address_generator_iact.vhd" \
    "${HDL_DIR}/address_generator_psum.vhd" \
    "${HDL_DIR}/control.vhd" \
    "${HDL_DIR}/control_address_generator.vhd" \
    "${HDL_DIR}/control_arch_rs.vhd" \
    "${HDL_DIR}/control_arch_alt_rs.vhd" \
    "${HDL_DIR}/accelerator.vhd" \
]
