rule:
  global:
    indentSize: 4
  if_002:
    parenthesis: "remove"
  type_010:
    disable: true
  type_011:
    disable: true
  variable_007:
    severity: "Warning"
  signal_007:
    disable: true
  length_001:
    disable: true
  component_019:
    disable: true
  conditional_waveforms_001:
    allow_single_line: true
